### ISSUE TITLE
Expired Time not counting in seconds

### ISSUE THREAD

**Issue by wilpar** [patman023/nysthimanual#18]
I put ExpiredTime into my rack, and it's counting at about 2.5 to 3 X real time.  Is this expected?  I already feel like I spend too much time inside VCV, this makes me feel even worse!

MacOS latest.
VCV Rack 1.1.6

**Comment by antoniotuzzi** [comment]
if you feel this is an issue you should open as an issue on the nysthi github
so I can prioritize a test

**Comment by patman023** [comment]
Opened on https://github.com/nysthi/nysthi/  .
Closing.
